### PR TITLE
NO-REF: Update version to 4.3.3 in package.json

### PR DESCRIPTION
**Pull request by jackiequach**
Update version to 4.3.3 in package.json

### CODE REVIEW

**Comment by samanthaandrews** [comment]
iirc i think the process for updating the package version number is done through the instructions here https://github.com/NYPL-Simplified/web-reader?tab=readme-ov-file#publishing-to-npm

is this correct, @kristojorg ? I don't know if I've ever even done a web-reader release before 😬

**Comment by jackiequach** [comment]
It is done there, but since I don't have permissions for the main branch it skipped that step.

**Comment by samanthaandrews** [comment]
> It is done there, but since I don't have permissions for the main branch it skipped that step.

I made you an admin... maybe that will allow you?!

**Review by samanthaandrews — APPROVED** [review]
I don't think merging this will make the release show up in GitHub, which is annoying. But I do see that 4.3.3 has been released on NPM!! 🎉 https://www.npmjs.com/package/@nypl/web-reader

**Pull request merged**
