### PR TITLE
Release 4.3.0

### PR DESCRIPTION
**Pull request by jackiequach**
- Update version number in package.json and package-lock.json

### CODE REVIEW

**Review by kristojorg — APPROVED** [review]
Looks good to me! Not sure if you already did this, but adding an entry to the changelog would also be appreciated. Thanks!

**Comment by samanthaandrews** [comment]
I actually don't think there needs to be a release branch for this, right? We just need to run through the npm publish process. The README says:

> To publish the package to [NPM](https://www.npmjs.com/package/@nypl/web-reader), you must first be added to the nypl organization within NPM.
Run npm run release from the main branch. Follow the prompts to add a new version, publish a release to github, and push to npm.

**Review by samanthaandrews — CHANGES_REQUESTED** [review]
@jackiequach can you create an npm account (if you don't have one already) and send me your username so I can add you to the NYPL org?

**Comment by kristojorg** [comment]
It's true we don't need a PR technically, but it's still find to bump the version number and changelog in this PR before doing that release process as documented from the main branch

**Comment by kristojorg** [comment]
That's a good point actually. I also forgot we don't have a CHANGELOG file but simply add the changes to the github release created when you run `npm run release`. So you can just do that on the main branch and add your changelog comments in the github release

**Comment by jackiequach** [comment]
@samanthaandrews @kristojorg I already ran `npm run release` and this PR was needed since I do not have write access to this repo for some reason.

**Comment by kristojorg** [comment]
Did the `npm run release` script work for you? I am not seeing a new release having been created in github

**Comment by kristojorg** [comment]
I do see 4.3.0 is released to NPM. So it looks like we just need to make the github release and possibly a tag and merge this PR to update the version number, is that right?

**Comment by kristojorg** [comment]
I just gave you write access specifically FYI. Let me know if you aren't able to create the github release and/or tag. Feel free to push the version change directly to the main branch along with the tag

**Review by samanthaandrews — APPROVED** [review]

**Pull request merged**
